string data_type
string sar_type
string sar_config
string policy_type_str
 
string cam_config
bool camactive_flag

string policy_type
uint32 vicon_delay_ms

string plane_type
string plane_config
float64 pos_x
float64 pos_y
float64 pos_z
float64 plane_angle_deg
 
float64 sim_speed
float64 sim_slowdown_speed
bool landing_slowdown_flag
 
uint32 logging_rate
bool show_console
 
float64 ref_mass
float64 ref_ixx
float64 ref_iyy
float64 ref_izz

float64 base_mass
float64 base_ixx
float64 base_iyy
float64 base_izz

float64 thrust_max
float64 c_tf

float64 tau_up
float64 tau_down
float64[3] trajacc_max
float64[3] trajjerck_max

float64 forward_reach
float64 gamma_eff
float64 l_eff
float64 k_pitch
float64 k_yaw

float64 leg_length
uint32 leg_angle

float64[2] prop_front_vec
float64[2] prop_rear_vec

float64 p_kp_xy
float64 p_kd_xy
float64 p_ki_xy
float64 i_range_xy

float64 p_kp_z
float64 p_kd_z
float64 p_ki_z
float64 i_range_z

float64 r_kp_xy
float64 r_kd_xy
float64 r_ki_xy
float64 i_range_r_xy

float64 r_kp_z
float64 r_kd_z
float64 r_ki_z
float64 i_range_r_z


